In [17]:
from svgelements import SVG, Circle, Ellipse, Path, Rect, Image
import re
import numpy as np

In [4]:
LABEL_TAG = re.compile(r'label="(.+?)"')
LABEL_PARSE = (
    r"([\w\W ()]+): \(?([-/\d \w\.%]+)\)?(?:, ?)?(?:\(?([-/\d \w\.%]+)\)?)?"
)

In [55]:
def _label_from_element(element):
    # TODO: rework label logic because we won't use the old one
    if found_label := re.findall(LABEL_TAG, element.string_xml()):
        label = found_label[0]
        label_name, *label_values = re.search(LABEL_PARSE, label).groups()

        return label, label_name, label_values

In [5]:
label_name, *label_values = re.search(LABEL_PARSE, found_label[0]).groups()

NameError: name 'found_label' is not defined

In [59]:
svg = SVG.parse(
    r"D:\University\Магистратура\Диплом Магистратура\Графики\PI-Tmax\Akram, R & Faqi, A & Jihad, W & Sherwani, G & Al-Ansari, N, 2021.svg",
    transform="rotate(180)",
)
for element in svg.elements(lambda elem: isinstance(elem, Path)):
    print(_label_from_element(element))

('MATURITY: Low Level Conversion, High Level Conversion', 'MATURITY', ['Low Level Conversion', 'High Level Conversion'])
('MATURITY: Immature, Oil Window', 'MATURITY', ['Immature', 'Oil Window'])
('MATURITY: Oil Window, Condensate-Wet Gas Zone', 'MATURITY', ['Oil Window', 'Condensate-Wet Gas Zone'])
('MATURITY: Condensate-Wet Gas Zone, Dry Gas Window', 'MATURITY', ['Condensate-Wet Gas Zone', 'Dry Gas Window'])


In [51]:
border_points = svg.union_bbox(svg.elements(lambda elem: not isinstance(elem, Image)), with_stroke=False)
edge_points = np.array(border_points).reshape(2, -1)
max_point = np.abs(edge_points.min(axis=0))
min_point = np.abs(edge_points.max(axis=0))

min_point, max_point  # (x_min, y_min), (x_max, y_max)

(array([103.52226,  30.5357 ]), array([794.     , 877.50763]))

In [ ]:
for element in svg.elements(lambda elem: isinstance(elem, Path)):
    print(element)

m -63.019531,-389.9375 c -252.319849,5.68434188608E-14 -504.639689,5.68434188608E-14 -756.959539,1.13686837722E-13 Z
m -283.92187,-20.5061 c 0,-123.1438 -5.68434188608E-14,-246.2876 -5.68434188608E-14,-369.4314 Z
m -410.52244,-20.5061 c 0,-123.1438 -5.68434188608E-14,-246.2876 -5.68434188608E-14,-369.4314 Z
m -536.10487,-20.5061 c 0,-136.83194 0,-273.66387 0,-410.49581 Z


In [52]:
border_points

(-794.0000000000001, -877.50763, -103.52226, -30.535699999999984)

In [53]:
border_points = []
# Get all Rectangles present in the image
# self.svg.union_bbox()
for element in svg.elements(lambda elem: isinstance(elem, Rect)):
    border_box = element.bbox()
    border_points.extend(
        [
            (border_box[0], border_box[1]),
            (border_box[2], border_box[3]),
        ]
    )

# Find edge points
edge_points = np.array(border_points)
max_point = np.abs(edge_points.min(axis=0))
min_point = np.abs(edge_points.max(axis=0))

min_point, max_point  # (x_min, y_min), (x_max, y_max)

(array([104.52226,  31.5357 ]), array([792.99998, 876.50762]))

In [54]:
edge_points

array([[-792.99998, -876.50762],
       [-104.52226,  -31.5357 ]])

In [72]:
from matplotlib.artist import ArtistInspector
from matplotlib.lines import Line2D
from matplotlib.patches import PathPatch

ArtistInspector(Line2D([0], [0])).properties()

{'agg_filter': None,
 'alpha': None,
 'animated': False,
 'antialiased': True,
 'bbox': Bbox([[0.0, 0.0], [0.0, 0.0]]),
 'children': [],
 'clip_box': None,
 'clip_on': True,
 'clip_path': None,
 'color': 'C0',
 'dash_capstyle': 'butt',
 'dash_joinstyle': 'round',
 'data': ([0], [0]),
 'drawstyle': 'default',
 'figure': None,
 'fillstyle': 'full',
 'gapcolor': None,
 'gid': None,
 'in_layout': True,
 'label': '',
 'linestyle': '-',
 'linewidth': 1.5,
 'marker': 'None',
 'markeredgecolor': 'C0',
 'markeredgewidth': 1.0,
 'markerfacecolor': 'C0',
 'markerfacecoloralt': 'none',
 'markersize': 6.0,
 'markevery': None,
 'mouseover': False,
 'path': Path(array([[0., 0.]]), None),
 'path_effects': [],
 'picker': None,
 'pickradius': 5,
 'rasterized': False,
 'sketch_params': None,
 'snap': None,
 'solid_capstyle': 'projecting',
 'solid_joinstyle': 'round',
 'tightbbox': Bbox([[0.0, 0.0], [0.0, 0.0]]),
 'transform': <matplotlib.transforms.IdentityTransform at 0x1a44a1b4d50>,
 'transformed_clip_